### PR TITLE
Daemon Refactor

### LINKED ISSUE #183: [Developer Story] When testing daemon, I have difficulty discerning tests responsibilities
### **Is your developer story related to a problem? Please describe.**
I am frustrated when navigating the tests done by the daemon. 

### **Describe the solution you'd like**
I would like that the tests are grouped into suites based by their responsibilities (eg. CPU, Process, Network, etc.)

### **Describe alternatives you've considered**
N/A

### **Additional context**
- test_report_module.py has become a God-test-class that has not been caught by sonarcloud.

### PR DESCRIPTION
**Pull request by arich94**
Refactors system_report.py file to wrap psutil methods and separate fetch methods into their own class
Refactors tests to separate based on class and OS
Fixes a bug where some linux systems would report memory type unknown

closes #183 , #196 , #208

### CODE REVIEW

**Review by shash3 — CHANGES_REQUESTED** [review]
Please fix the security hotspots, code smells and code duplication
image

**Comment by Pyxsys** [comment]
Updated initial PR comment to fix typo (*bug, not big)

**Comment by Pyxsys** [comment]
> Please fix the security hotspots, code smells and code duplication image

Sonar cloud issues addressed.

**Review by shash3 — APPROVED** [review]
Good work on the refactoring. 
All  sonarcloud issue have been addressed!

**Review by sachaelkaim — APPROVED** [review]
Refactoring is good.
Sonar cloud issues addressed.

**Pull request merged**
