### PR TITLE
Adding fix for flaky initialization and disk fetching

### LINKED ISSUE #237: [BUG] Daemon occasionally doesn't initialize
### **To Reproduce**
1. Start daemon via 'celebi' command

### **Expected behavior**
Daemon starts.

### **Device (please complete the following information):**
 - type: Raspberry Pi
 - model: Raspberry Pi 3 Model B Plus Rev 1.3
 - OS: Debian GNU/Linux 11 (bullseye)
 - version: 11

### **Suggested fix**
Add explicit parent initialization to Threading subclass.

### LINKED ISSUE #238: [BUG] Daemon does not get disk info for incongruent device/mountpoints
### **Describe the bug**
If the running system has an incongruency between device and mountpoint, daemon fails to fetch disk info

### **To Reproduce**
1. Ensure disk device and mountpoint are incongruent
2. Start daemon via 'celebi' command

### **Expected behavior**
Daemon successfully fetches disk information.

### **Device (please complete the following information):**
 - type: Raspberry Pi
 - model: Raspberry Pi 3 Model B Plus Rev 1.3
 - OS: Debian GNU/Linux 11 (bullseye)
 - version: 11

### **Suggested fix**
Change reference of disk_partitions element to use 'mountpoint' instead of 'device'.

### PR DESCRIPTION
**Pull request by Pyxsys**
### Daemon
+ Added fix for flaky initialization of Runner
+ Added fix for Flaky behaviour for disk routes  
+ Ran and updated load test for release 3
+ Added Analytics and Dashboard Videos to ReadMe
## Tickets  
Fixes #237 
Fixes #238

### CODE REVIEW

**Comment by Pyxsys** [comment]
@shash3 Please update PR summary with changes

**Comment by shash3** [comment]
> @shash3 Please update PR summary with changes

It has already been done :)

**Review by DerekRuiz — APPROVED** [review]
Good for moving tests reports to new folder for separate releases
Adding test reports for Analytics page looks proper

**Review by NathanZiri — APPROVED** [review]
Seem like everything works, all tests passed, good work

**Pull request merged**
