### PR TITLE
Devices page

### LINKED ISSUE #188: [User Story] As an application user, I would like the devices table page to be straightforward, responsive to different device screen sizes, with a design that matches the rest of the application.
### **Is your user story related to a problem? Please describe.**
It frustrates me that the devices page does not aesthetically match the rest of the application and that it becomes harder to use on larger and smaller device screen sizes. 

### **Describe the solution you'd like**
I'd like the devices page to be updated with a modern style that matches the other pages of the application and that, depending on the screen size I am using, for the application to be responsive and resize accordingly. 

### **Additional context**
The Figma diagrams will be used to guide the implementation.

### LINKED ISSUE #190: [BUG] A new web app bug
### **Describe the bug**
When toggling the accordion multiple times in a row, multiple white dots along the top and the side of the accordion Card component.

### **To Reproduce**
1. Navigate to the Device Detail Page
2. Click on the "Device" Accordion Card Header six (6) times in rapid succession
3. See Error: white dots along the top corners and the left side appear

### **Expected behavior**
The expected behaviour is to not have the white dots appear when toggling the accordion card open and close.

### **Suggested fix**
A proposed solution is to hide the white dots somehow or change the module to get the accordion effect.

### LINKED ISSUE #191: [BUG] A new web app bug
### **Describe the bug**
When you click the search bar on the devices page after it has just loaded, the navbar side menu is triggered and displayed.

### **To Reproduce**
1. Navigate to the Devices Page
2. Click on the search bar
3. See Error: side menu will open

### **Expected behavior**
The navbar side menu should only be triggered to open when clicking the hamburger icon.

### PR DESCRIPTION
**Pull request by j-eltayar**
### Devices Table Page
+ Pie wheel animated svg component from the device detail page
+ Wifi animated svg component from the device detail page
+ Bootstrap/scss 
+ Responsive design
+ Updated table columns and behavior
+ Pagination functionality
## Tickets
* Closes #188
* Closes #190
* Closes #191

### CODE REVIEW

**Review by shash3 — CHANGES_REQUESTED** [review]
* The UUID should be in white and not blue
*  We should have a search bar next to the UUID like the previous version that filters through all devices
* picture below for reference:
image

**Comment by DerekRuiz** [comment]
> * The UUID should be in white and not blue
> * We should have a search bar next to the UUID like the previous version that filters through all devices
> * picture below for reference:
>   image

I believe this can be addressed in a separate PR to keep this one more inline with what is explained in the summary

**Comment by shash3** [comment]
> > * The UUID should be in white and not blue
> > * We should have a search bar next to the UUID like the previous version that filters through all devices
> > * picture below for reference:
> >   image
> 
> I believe this can be addressed in a separate PR to keep this one more inline with what is explained in the summary

That sounds good. Just point number 1 needs to be addressed then @j-eltayar 
*  The UUID should be in white and not blue

**Comment by shash3** [comment]
@j-eltayar  
After a call with the team we decided to Add the search in the UUID column and remove the LIMIT from the query.
image

**Review by shash3 — APPROVED** [review]
* All changes requested have been fulfilled. 
* Good work with the overall look of the table of devices and the pie wheels and wifi bar from the details page.

**Review by DerekRuiz — APPROVED** [review]
* Devices Table have good css
* Code for table looks great

**Pull request merged**
