### PR TITLE
Static disk

### LINKED ISSUE #17: [User Story] As a data analyst, I would like to know the disk usage of a specific device
### **Is your user story related to a problem? Please describe.**
It frustrates me when I cannot easily discern the disk usage of a Raspberry Pi computer that my machines are relying on.

### **Describe the solution you'd like**
I'd like to be able to easily view the disk usage data as provided by the daemon.

### **Describe alternatives you've considered**
Manually seeking disk usage data is troublesome and difficult.

### **Additional context**
The disk usage data should include:
- Active time (%)
- Average response time (ms)
- Read speed (nB/s)
- Write speed (nB/s)

### LINKED ISSUE #18: [User Story] As a systems engineer, I would like to know the disk specifications of a specific device
### **Is your user story related to a problem? Please describe.**
As a systems engineer, I am frustrated by not knowing the Disk specifications of the device I am monitoring.

### **Describe the solution you'd like**
I would like to see Disk specifications in my data and displayed on the application so I can easily associate Disk usage with the device I am monitoring.

### **Describe alternatives you've considered**
Obtaining the information from a command line or shell-only method is tedious and not convenient.

### **Additional context**
The information can be sent to either SQL-style tables or a MongoDB collection.
The disk specifications should include:
- Capacity (nB)
- Type (SSD, HDD, etc.)

### PR DESCRIPTION
**Pull request by Pyxsys**
### Server
+ Updated api/daemon.js to accept & process static disk info from payload
+ Updated api/daemon.js to accept & process dynamic disk info from payload
+ Added tests for disk info
+ Updated tests
### Daemon
+ Added fetching static disk info
+ Added fetching disk partition info
+ Added fetching disk I/O info
+ Updated tests
## Tickets
* Closes #17
* Closes #18

### CODE REVIEW

**Review by DerekRuiz — CHANGES_REQUESTED** [review]
image
- Fix code smells
- Fix Security Hotspots

**Comment by DerekRuiz** [comment]
@shash3, @sachaelkaim, and @j-eltayar Please check why the E2E and Client Tests are failing when the files have not been changed

**Comment by Pyxsys** [comment]
> 

Addressed sonarcloud quality gate with commit 64425422f34b382096610bf8bc28c6cfcb598855

**Review by DerekRuiz — CHANGES_REQUESTED** [review]
Code Smells resolved
- Fix E2E and Client Tests
image

**Comment by Pyxsys** [comment]
> Code Smells resolved
> 
> * Fix E2E and Client Tests
>   image

@shash3, @sachaelkaim, and @j-eltayar Please advise ASAP.

**Comment by sachaelkaim** [comment]
issue resolved @Pyxsys @DerekRuiz

**Review by DerekRuiz — APPROVED** [review]
- All changes provided
- Added Disk info looks good
- Disk tests are acceptable

**Review by sachaelkaim — APPROVED** [review]

**Pull request merged**
