### PR TITLE
UI frontend implementation of notifications into Front-End Login and Signup

### PR DESCRIPTION
**Pull request by j-eltayar**
The notification service implemented in #151 was implemented in the front end, specifically the login and signup page.

Now, whenever a user enters an invalid input into a field and tries to log in or signup they will be prompted with an error notification.  

For example:

image

Also when a user successfully logs in or signs up they will be prompted by a success notification.

For example:

image

### CODE REVIEW

**Review by DerekRuiz — APPROVED** [review]
Login Page looks Good
Error Validation & User notifications looks proper

**Review by shash3 — CHANGES_REQUESTED** [review]
Missing Cases:

** For login page
- [x] When email entered is incorrect
- [x] When password entered is incorrect

** For Signup page
- [x] When email is already in use

**Comment by sachaelkaim** [comment]
Everything looks good.
is it possible to remove .idea/inspectionProfiles in root?

**Review by shash3 — CHANGES_REQUESTED** [review]
All prior concerns have been addressed. 
requesting the removal of `.idea/inspectionProfiles` in the root of the project.

**Review by shash3 — APPROVED** [review]
All Concerns have been addressed. Good work on the notifications for all cases. This will allow the user to pin point where they're going wrong.

**Review by shash3 — CHANGES_REQUESTED** [review]
Please fix the code smell issue prior to merging.
`return await axios`  on line 90 of **inputValidation.tsx** the `await` is redundant in this line

**Review by shash3 — APPROVED** [review]
thank you @DerekRuiz for addressing the issue.

**Pull request merged**
