### PR TITLE
UI frontend

### PR DESCRIPTION
**Pull request by ashrafwkhalil**
created and implemented structure for entire frontend. 
implemented signup page, login page, device page, device detail page, and navbar.
implemented navigation and routes between pages
implemented api endpoints, and relevant routing
modified schemas to separate dynamic and static data
successfully integrated database with front-end, allowing for the displaying of actual database data, and not dummy data. 
added folder in client to store schema information in form of interfaces

### CODE REVIEW

**Review by DerekRuiz — CHANGES_REQUESTED** [review]
Fix amount of code duplication, it is currently at 7.1%
Fix the amount of code smells it is currently at 21

**Review by shash3 — CHANGES_REQUESTED** [review]
Remove the disable-eslint on deviceDetailPage.tsx

**Review by DerekRuiz — APPROVED** [review]
Accepted that code smells reduced to 0
Good to reduce code duplication to 0%

UI front end looks good:
- [x] the login/logout reviewed
- [ ] the device table page reviewed
- [x] the device detail page reviewed

**Review by shash3 — APPROVED** [review]
Everything seems to be in order. Couple of suggestions for future development:

- add arrows on the devices table to show the ability to sort. 
- remove PID next to the search box on the devices page

Tested out all key implementations such as sign up, login and devicedetails

**Pull request merged**
