### PR TITLE
Static network

### LINKED ISSUE #20: [User Story] As a systems engineer, I would like to know the Wi-Fi specifications of a specific device
### **Is your user story related to a problem? Please describe.**
As a systems engineer, I am frustrated by not knowing the Wi-Fi specifications of the device I am monitoring.

### **Describe the solution you'd like**
I would like to see Wi-Fi specifications in my data and displayed on the application so I can easily associate Wi-Fi usage with the device I am monitoring.

### **Describe alternatives you've considered**
Obtaining the information from a command line or shell-only method is tedious and not convenient.

### **Additional context**
The information can be sent to either SQL-style tables or a MongoDB collection.
The wi-fi specifications should include:
- Adapter name
- SSID
- Connection type
- IPv4 address
- IPv6 address

### PR DESCRIPTION
**Pull request by Pyxsys**
### Server
+ Updated api/daemon.js to accept & process static wifi info from payload
+ Enhanced tests and test artifacts to handle static wifi info
### Daemon
+ Added  "network_adapter" field to configuration files
+ Added fetching static wifi info for a given adapter (defaulting to OS defaults if non given)
  - Adapter name
  - SSID
  - Connection type
  - IPv4 address
  - IPv6 address
+ Updated tests
## Tickets
* Closes #20

### CODE REVIEW

**Comment by Pyxsys** [comment]
> SonarCloud Quality Gate failed.    Quality Gate failed
> 
> [Bug](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=SECURITY_HOTSPOT) [D](https://sonarcloud.io/project/security_hotspots?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=SECURITY_HOTSPOT) [5 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=CODE_SMELL) [4 Code Smells](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=Pyxsys_ttg-healthcheck&pullRequest=187) No Coverage information [](https://sonarcloud.io/component_measures?id=Pyxsys_ttg-healthcheck&pullRequest=187&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=Pyxsys_ttg-healthcheck&pullRequest=187&metric=new_duplicated_lines_density&view=list)

Security hotspots are pointing to the dummy values for ip addresses created for the mocks. these are being marked as safe.

**Comment by Pyxsys** [comment]
> Kudos, SonarCloud Quality Gate passed!    Quality Gate passed
> 
> [Bug](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=CODE_SMELL) [4 Code Smells](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=Pyxsys_ttg-healthcheck&pullRequest=187) No Coverage information [](https://sonarcloud.io/component_measures?id=Pyxsys_ttg-healthcheck&pullRequest=187&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=Pyxsys_ttg-healthcheck&pullRequest=187&metric=new_duplicated_lines_density&view=list)

Following commits shall address these code smells

**Comment by Pyxsys** [comment]
> SonarCloud Quality Gate failed.    Quality Gate failed
> 
> [Bug](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=SECURITY_HOTSPOT) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=Pyxsys_ttg-healthcheck&pullRequest=187&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=Pyxsys_ttg-healthcheck&pullRequest=187) No Coverage information [](https://sonarcloud.io/component_measures?id=Pyxsys_ttg-healthcheck&pullRequest=187&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=Pyxsys_ttg-healthcheck&pullRequest=187&metric=new_duplicated_lines_density&view=list)

Again dummy IP value. marked as safe.

**Comment by Pyxsys** [comment]
@shash3 Do you know what could be going on here?
The test files themselves are unable to be imported within the Actions CI/CD.

image

**Comment by shash3** [comment]
> @shash3 Do you know what could be going on here? The test files themselves are unable to be imported within the Actions CI/CD.
> 
> image

I'm not sure what is causing the error. I can have a look

**Comment by shash3** [comment]
@Pyxsys the error is originating from `daemon/src/system_report.py` line 1.

**Review by shash3 — APPROVED** [review]
* All changes provided
* Added Network info looks good
* Network tests are acceptable

**Review by DerekRuiz — APPROVED** [review]
* Extracting Network functions look acceptable
* Tests associated with network extraction are good
* Updating the server information with the wifi (network) information is good

**Pull request merged**
