### PR TITLE
Network strength

### LINKED ISSUE #21: [User Story] As a data analyst, I would like to know the Wi-Fi usage of a specific device
### **Is your user story related to a problem? Please describe.**
It frustrates me when I cannot easily discern the wi-fi usage of a Raspberry Pi computer that my machines are relying on.

### **Describe the solution you'd like**
I'd like to be able to easily view the wi-fi usage data as provided by the daemon.

### **Describe alternatives you've considered**
Manually seeking wi-fi usage data is troublesome and difficult.

### **Additional context**
The wi-fi usage data should include:
- send speed (Kbps)
- Receive speed (Kbps)
- Signal strength (hi, med, low)

### PR DESCRIPTION
**Pull request by arich94**
- added fetch method to SysReport to collect signal strength from Windows and Linux systems
- added signal strength to network report
- added signal strength endpoint to database

closes #21

### CODE REVIEW

**Comment by Pyxsys** [comment]
The failing tests will need to be mocked as github actions does not support a wifi-adapter on it's virtual environment

**Review by DerekRuiz — COMMENTED** [review]
Please fix the code smell
image

**Comment by arich94** [comment]
> Please fix the code smell image

I will, I'm just getting the tests to pass first!

**Comment by arich94** [comment]
PR temporarily closed while branch is being revised

**Comment by arich94** [comment]
Reopened pull request

**Review by Pyxsys — APPROVED** [review]
Good call on abstracting the psutil constants in a wrapper.
Step values for signal strength is a sufficient middleground for inconsistent units returned by OS.

**Review by DerekRuiz — APPROVED** [review]
The Network signal strength looks good
Refactored methods are accepted

**Pull request merged**
