### PR TITLE
Restyle login and register

### PR DESCRIPTION
**Pull request by sachaelkaim**
Login and register page restyled.
Has been made compatible for mobile and large screen.
Dynamic layout.
Issue reference: #164

### CODE REVIEW

**Review by arich94 — CHANGES_REQUESTED** [review]
Hey, can you check the code smell and also watch out for the duplication. Thanks!

**Review by j-eltayar — CHANGES_REQUESTED** [review]
There seems to be a code smell as well as some duplicate code that needs to be refactored before merging. As for the changes, really well done, it seems fluid and the proportions very well managed. 

image

**Review by DerekRuiz — APPROVED** [review]
- Media Query for SCSS looks good
- Updated Tests look acceptable

**Review by arich94 — APPROVED** [review]
Looks good now. Thanks!

**Comment by arich94** [comment]
[This comment can be ignored. It is to test GitHub/Discord Webhook functionality]

**Review by Pyxsys — CHANGES_REQUESTED** [review]
Blocking PR due to request from @sachaelkaim

**Review by arich94 — CHANGES_REQUESTED** [review]
Requesting changes to address found footer bug.

**Comment by sachaelkaim** [comment]
Footer Bug is fixed.

**Review by shash3 — APPROVED** [review]
Revamped landing page looks clean. 
Updated test also acceptable.
Good work! 😃

**Review by j-eltayar — APPROVED** [review]
Good job on dealing with the duplicate code and the smell! Seems all good.

**Review by Pyxsys — APPROVED** [review]
Block request lifted with ec5f4a14811953b8e11906a3f9b6a22186dd1da9

**Review by arich94 — APPROVED** [review]
Thanks for making the changes, it looks good!

**Pull request merged**
