### PR TITLE
Daemon peripherals

### LINKED ISSUE #4: [User Story] As a systems engineer, I would like to know about the peripherals connected to my remote device
### **Is your user story related to a problem? Please describe.**
As a systems engineer, I am frustrated by the steps needed to retrieve an informative list of peripherals connected to my remote rasberryPi.

### **Describe the solution you'd like**
I would like peripheral information streamed to my database so that I can quickly refer and retrieve the information.

### **Describe alternatives you've considered**
Obtaining the information from a shell-only method is tedious and is not convenient.
Connecting to a remote desktop is too slow and restrictive for my needs.

### **Additional context**
The information can be sent to either SQL-style tables or a MongoDB collection.
Info I would like to be sent is:
- Time data was gathered
- Device name
- Device description
- Connection type (USB, Bluetooth, etc.)
- Status
- Provider
- Hardware ID

The rate at which updated information is sent should be adjustable.

### PR DESCRIPTION
**Pull request by Pyxsys**
### Server
+ Added "peripheral" model
+ Updated api/daemon.js to accept & process peripheral info from payload
+ Added test to verify integrity of peripheral data
### Daemon
+ Added fetching connected USB devices to report (Linux Only)
  - Hardware ID
  - Connection (USB)
  - Name

+ Updated tests
## Tickets
* Closes #4

### CODE REVIEW

**Comment by DerekRuiz** [comment]
Please fix the Sonar Cloud detected bug associated with Class Functions
image

**Comment by Pyxsys** [comment]
> Please fix the Sonar Cloud detected bug associated with Class Functions image

Added missing decorator with [c67e394](https://github.com/Pyxsys/ttg-healthcheck/pull/223/commits/c67e39439f55c5a2ebad9a6504649bff2b91eda8)

**Comment by arich94** [comment]
image
Not sure if you touched UI or if there's a flaky test, but please check on this.

**Review by DerekRuiz — APPROVED** [review]
The tests reports look good
New Peripheral schema is nicely added

**Review by arich94 — APPROVED** [review]
Good work following the already established structure when adding this new check. This goes for both the daemon side and the api/server side. Well done.

**Pull request merged**
