### PR TITLE
Dashboard Page With Specific Device Widgets

### LINKED ISSUE #78: [User Story] As a web developer, I want a dashboard that provides a quick overview of critical performance parameters and allows you to keep track of your infrastructure's health.
### **Is your user story related to a problem? Please describe.**
I'm frustrated when my web application lacks a dashboard with innovative features.

### **Describe the solution you'd like**
I want a web application that contains a dashboard that provides a quick overview of critical performance parameters and allows you to keep track of your infrastructure's health. 

### **Describe alternatives you've considered**
There is no suitable alternative to this.

### **Additional context**
No further context is necessary.

### LINKED ISSUE #194: [BUG] Dashboard - Unable To Open Hamburger In Dashboard
### **Describe the bug**
After opening the "Add New Widget" modal in the dashboard, I am unable to open and close the hamburger (the three horizontal lines in the navbar) to navigate to the other pages. It works fine if I do not open the modal, however once I open and close the modal, the hamburger is inaccessible.

### **To Reproduce**
1. Navigate to the dashboard page
2. Click on the Plus icon to open the "Add New Widget" modal
3. Close the modal (either click cancel button or click off the modal)
4. Click on the hamburger in the navbar.
5. The sidebar will not open

### **Expected behavior**
I expect to be able to open the sidebar after using the modal feature.

### **Suggested fix**
I have tracked the issue to the event listener that closes the sidebar when clicking off of the sidebar. When I disabled the event listener, I am able to use both the modal and the navbar independently again.

### PR DESCRIPTION
**Pull request by DerekRuiz**
Adds Dashboard page with the following functionality:
* Add a widget from a selection of possible widgets.
* Clear all widgets
* Remove a single widget
* Save the existing dashboard
* Revert to the last saved dashboard
* Can collapse a widget
* Resizes with regard to screen size for mobile support
---
Closes #78, #79 
Resolves #194

### CODE REVIEW

**Review by shash3 — CHANGES_REQUESTED** [review]
*  Avoid the use of `page` use `component` instead (e.g. dashboard_component) or if its already under the component folder, you can completely remove it all.
*  Please fix the issues with the tests failing. This is most likely due to the change of name.

**Comment by DerekRuiz** [comment]
@shash3
Moved main components into a separate Page folder and removed the suffix "Page" from files for consistent naming convention.
Fixed UI Tests to work with the new Dashboard.

**Review by shash3 — APPROVED** [review]
All concerns have been addressed. 
Everything looks good now

**Review by sachaelkaim — APPROVED** [review]
All features are working correctly. great work!

**Pull request merged**
