### PR TITLE
Analytics page

### LINKED ISSUE #5: [User Story] As data analyst I would like to see graphs displaying real time data regarding the raspberryPi of my choice.
### Is your user story related to a problem? Please describe.
As a data analyst. I am bothered by the lack of direct and concise data given to me about the raspberryPi's.

### Describe the solution you'd like
I would prefer if I was able to see charts showing statistics like, CPU usage or network information  over the last 24 and 48 hours as well as over the last week and month.

### Describe alternatives you've considered
As a data analyst I can, for the time being, only receive the data given to me so there is not much for me to do.

### Additional context
The information can be sent to either SQL-style tables or a MongoDB collection which can then be displayed via a react app.
Info I would like to be sent is:

Time data was gathered
Name of process
PID of process
CPU usage
Status
Network info
Number of threads related to process
The rate at which updated information is sent should be adjustable.

### LINKED ISSUE #6: [User Story] As a data analyst i would like to be able to download a full CSV file with all data from a time period of my choice.
### Is your user story related to a problem? Please describe.
As a data analyst I may find that some of the graphs provided to me by issue #5 may not be siffient and therefore want to be able to make my own.

### Describe the solution you'd like
I would like to be able be able to download all the data being streamed from the rasperryPi's for a given period of  time of my choosing.

### Describe alternatives you've considered
In order to do this i would have to ask a coworker who works directly with the raspberryPi's to send me the information i was looking for.

### Additional context
The information can be sent to either SQL-style tables or a MongoDB collection.
Info I would like to be sent is:

Time data was gathered
Name of process
PID of process
CPU usage
Status
Network info
Number of threads related to process
The rate at which updated information is sent should be adjustable.

### LINKED ISSUE #32: [User Story] As a data analyst, I want the API to identify abnormalities and errors in data and report them to the web application
### **Is your user story related to a problem? Please describe.**
I get frustrated when there is an error or abnormality I don't know about, and therefore cannot fix.

### **Describe the solution you'd like**
If the API detects abnormal behavior in the raspberry pi computer, it should report it to the web application so that the data analyst can easily identify it and begin thinking of potential solutions.

### **Describe alternatives you've considered**
The API is the best part of the project to handle this task as it communicates with the database that holds the information, and the web application which the user will have access to.

### **Additional context**
This may alert the user via notification.
This may have a display area associated with the machine that is not functioning.

### LINKED ISSUE #56: [User Story] As a data analyst, I want to be able to zoom in and out of graphs.
### **Is your user story related to a problem? Please describe.**
I'm frustrated when I can't zoom in/out of my graphs.

### **Describe the solution you'd like**
I want graphs to be interactable so they allow me to zoom in/out in order to better analyze.

### **Describe alternatives you've considered**
There is no suitable alternative to this.

### **Additional context**
No further context is necessary.

### LINKED ISSUE #57: [User Story] As a data analyst, I want the web application to allow partitioning data in graphs.
### **Is your user story related to a problem? Please describe.**
I'm frustrated when I can't partition data in my graphs.

### **Describe the solution you'd like**
I want the web application to make graphs interactable so that I can partition the range of my data.

### **Describe alternatives you've considered**
There is no suitable alternative to this.

### **Additional context**
No further context is necessary.

### LINKED ISSUE #68: [User Story] As a web developer, I want the users to be able to set thresholds to alter specific aspects of performance for the system.
### **Is your user story related to a problem? Please describe.**
I'm frustrated when I can't change the performance settings for the web application.

### **Describe the solution you'd like**
I want the web application to allow users to set thresholds for irregular processes or system activity in the web application (e.g. High Usage, Low memory).

### **Describe alternatives you've considered**
There is no suitable alternative to this.

### **Additional context**
No further context is necessary.

### LINKED ISSUE #69: [User Story] As a web developer, I want my web application to alert users/operators of irregular processes or system activities.
### **Is your user story related to a problem? Please describe.**
I'm frustrated when my web application doesn't alert users/operators of irregular processes and system activities.

### **Describe the solution you'd like**
I want my web application to send alerts to the user/operators if they encounter an irregular process or if a activity occurs in the system

### **Describe alternatives you've considered**
There is no suitable alternative to this.

### **Additional context**
No further context is necessary.

### PR DESCRIPTION
**Pull request by ashrafwkhalil**
- Implemented Entire Analytics Page

1. Created sortWithThreshold widget, which displays sorted list of devices displaying certain metric, and displays number of devices above user set threshold
2. Implemented graph feature, which allows user to select devices and see historic data about them in relation to any metric either in the form of hourly averages over the past day, or daily averages over the past month or week
3. formatted page to have 3 widgets on the top and graph UI and settings below the widgets

closes #5
closes #6
closes #32
closes #56
closes #57
closes #68
closes #69

### CODE REVIEW

**Review by arich94 — CHANGES_REQUESTED** [review]
Please fix the code smells identified by SonarCloud

**Review by sachaelkaim — APPROVED** [review]
All issues have been addressed. (code smell, csv, cursor on delete, name of page on navbar)

**Review by DerekRuiz — APPROVED** [review]
Very nice work integrating the 3rd party chart service.
The Threshold panels look good.
The Graph looks very usable

**Review by arich94 — APPROVED** [review]
Thanks for making the changes!

**Pull request merged**
