### PR TITLE
Process cpu usage

### LINKED ISSUE #9: [User Story] As a systems engineer, I would like to know the CPU usage of active processes on my remote device
### **Is your user story related to a problem? Please describe.**
As a systems engineer, I am frustrated by the steps needed to retrieve the CPU usage information of running processes on my remote rasberryPi.

### **Describe the solution you'd like**
I would like to see the CPU usage, as a percentage, of processes running on my remote device in my database so that I may quickly refer and retrieve the information.

### **Describe alternatives you've considered**
Obtaining the information from a shell-only method is tedious and is not convenient.

### **Additional context**
The information can be sent to either SQL-style tables or as part of a MongoDB document.
The CPU usage information should be timestamped so that I may easily determine periods of intensive usage.
Related to issue #1

### PR DESCRIPTION
**Pull request by Pyxsys**
* Removed duplication in daemon testing.
* Updated root README to contain daemon info.
* Refactored Daemon API tests to be more generic.
* Added reporting of cpu-usage by process.

- Closes #9

### CODE REVIEW

**Review by arich94 — APPROVED** [review]
The code looks good. I particularly like the refactoring work, it makes it a lot easier to understand.

**Review by DerekRuiz — APPROVED** [review]
Readme update is good
Tests looks good

**Review by shash3 — CHANGES_REQUESTED** [review]
Change to the file name requested. 
Change daemon_endpoint to just daemon as all files in the API folder will be endpoints

**Comment by sachaelkaim** [comment]
This is creating a codesmell due to an empty block.
` processes.forEach(function(proc){
    if(proc.name === 'System Idle Process'){}

Consider defining the type for the queries coming in the endpoints, as this could sometimes potentially cause a security issue.

**Comment by Pyxsys** [comment]
> Change to the file name requested. Change daemon_endpoint to just daemon as all files in the API folder will be endpoints

Filename has been changed in [recent commit](https://github.com/Pyxsys/ttg-healthcheck/pull/139/commits/1f77601e24ee4d7764443b4a554de3285f85d67e)

**Review by shash3 — APPROVED** [review]
Issues have been addressed.

**Pull request merged**
