### PR TITLE
Process cpu status

### PR DESCRIPTION
**Pull request by arich94**
- updates system report to include statuses of applications
- update process model to include status
- updates daemon endpoints to receive status
- counts number of threads running and sleeping
- updates tests to account for statuses

This pull request will close issue #8

### CODE REVIEW

**Review by DerekRuiz — APPROVED** [review]
Adding status to report looks good.
Tests for documenting logs is accepted

**Review by shash3 — CHANGES_REQUESTED** [review]
There is a minor code smell issue that can be dealt with. I believe it is the right thing to do right now and get ahead of it.

**Review by shash3 — APPROVED** [review]
all concern have been addressed!
Everything else looks perfect. Good work!

**Comment by NathanZiri** [comment]
Looks good

**Pull request merged**
