### PR TITLE
Cypress Implementation

### PR DESCRIPTION
**Pull request by sachaelkaim**
**Cypress setup** 

**Cypress tests for E2E** #161 #162 

- login
- register
- logout

**Cypress tests for UI** #47 #163
- login page
- register page 

setup GH actions partially completed ( E2E completed, #165)

### CODE REVIEW

**Comment by sachaelkaim** [comment]
Trying to run back-end, then build front end on gh actions to do the testing but build gets stuck after running the backend on GH actions and does not continue.

**Comment by shash3** [comment]
@sachaelkaim Are you trying to set up GH action for UI tests or for Acceptance tests ?

**Comment by shash3** [comment]
We might have to look into [Cypress](https://www.cypress.io/). Cypress is a JavaScript End to End Testing Framework and is free to use for our Github Project. We can simply install this as our dependency using `npm install cypress`

**Comment by sachaelkaim** [comment]
We are officially switching over from Selenium to Cypress.

**Review by DerekRuiz — APPROVED** [review]
Front End tests look good
End to end tests look good
Separating github workflows into separate jobs is smart
Cypress using environment variable is great for future development
Overall implementation looks beautiful

**Review by Pyxsys — COMMENTED** [review]
E2E tests are well written and are understandable.
For understanding; @sachaelkaim @shash3 @DerekRuiz @j-eltayar Could one of you please explain why are two 'cypress' directories, one in root and one under `/client`. 

Will approve once question above is answered.

**Review by NathanZiri — DISMISSED** [review]
Looks good

**Comment by sachaelkaim** [comment]
> E2E tests are well written and are understandable. For understanding; @sachaelkaim @shash3 @DerekRuiz @j-eltayar Could one of you please explain why are two 'cypress' directories, one in root and one under `/client`.
> 
> Will approve once question above is answered.

cypress root is for e2e
cypress fe is for ui
We can probably be able to have only one cypress directory for both e2e and UI. Shashank said he would look into doing this.

**Comment by Pyxsys** [comment]
> > E2E tests are well written and are understandable. For understanding; @sachaelkaim @shash3 @DerekRuiz @j-eltayar Could one of you please explain why are two 'cypress' directories, one in root and one under `/client`.
> > Will approve once question above is answered.
> 
> cypress root is for e2e cypress fe is for ui We can probably be able to have only one cypress directory for both e2e and UI. Shashank said he would look into doing this.
Thank you for the clarification.

**Review by Pyxsys — APPROVED** [review]
Approving as stated

**Pull request merged**
