### PR TITLE
Add refractor test locations, add front-end tests and update read me.

### PR DESCRIPTION
**Pull request by j-eltayar**
### Changes
* Moved all front-end tests to root cypress directory and updated integration folder to separate front-end tests from e2e tests.
* Updated the README accordingly.
* Added front-end tests for both devices page and device detail page.

### Coverage Before
image
### Coverage After
image

### CODE REVIEW

**Comment by Pyxsys** [comment]
> 

please address and advise the security hotspots

**Comment by arich94** [comment]
Watch out for that code duplication as well.

**Comment by j-eltayar** [comment]
The last two tests will never pass as in this pr they are merged into a single test suite for UI/Integration testing.

**Comment by arich94** [comment]
> The last two tests will never pass as in this pr they are merged into a single test suite for UI/Integration testing.

I'm okay with it, as long as all tests are passing once the PR is merged -- we want to make sure our build is still passing.

**Review by DerekRuiz — APPROVED** [review]
* Refactoring Client and E2E tests looks good
* New Client Tests are great
* Test Coverage over 80% is fantastic

**Review by arich94 — APPROVED** [review]
Great work! Glad to see that code coverage go up

**Pull request merged**
