### PR TITLE
Endpoints on server side

### LINKED ISSUE #33: [User Story] As a systems engineer, I want the API to validate requests from the web application to the system structure and return appropriate responses
### **Is your user story related to a problem? Please describe.**
It frustrates me when the web application does not function as intended due to a server-side issue.

### **Describe the solution you'd like**
I want the API to be able to validate requests from the web application appropriately so that it can return an appropriate response.

### **Describe alternatives you've considered**
There is no suitable alternative to this.

### **Additional context**
No further context is necessary.

### LINKED ISSUE #88: API Communication Between Web Application and Database
The API is used to communicate and pass data to and from the database and the web application.

### LINKED ISSUE #116: [Bug] ESLint crash front end and Back end on pre-commit hook
Error running npm run dev in the front-end. Eslint causing issues

`Using 'CRLF' Linebreaks Instead of 'LF' Linebreaks`
#91

### PR DESCRIPTION
**Pull request by shash3**
### For Device Model 
- [x] Get a specific device given deviceId or name
- [x] Get multiple devices given a limit (number of devices to retrieve), 1 or more attributes or a filter ( order by an attribute, increasing and negative)
### For Log Models
- [x] Get multiple entries for a single device. Given the number of devices desired and deviceID, get the most recent entries for that device.
- [x] Get multiple entries within a timestamp. Given two timestamp, retrieve all entries. Add an option to specify a single device.
- [x] Get multiple entries given an attribute with the ability to add a limit and order by filter

* Closes #88 
* Closes #33 
* Fixed #116

### CODE REVIEW

**Comment by sachaelkaim** [comment]
code smell found in log/device api files
` res.status(200).json(device) return`

**Comment by sachaelkaim** [comment]
missing`"npm run test:staged --prefix server" in package.jsons
do not merge PR

**Comment by shash3** [comment]
> missing `"npm run test:staged --prefix server"` and `"npm run test:staged --prefix client"` in package.jsons do not merge PR

Will add the missing script

**Comment by shash3** [comment]
@DerekRuiz The change_stream.test.js that you have written seems to fail occasionally, can you take a look please

**Review by DerekRuiz — APPROVED** [review]
API endpoints for Device Collection looks good
API endpoints for the different Log Collections approved
Filter function properly extracts parameters
Good catch for the type in the Schema

**Review by arich94 — APPROVED** [review]
It looks good to me.

**Pull request merged**
